# Generated by Django 6.1 on 2026-08-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ai_solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
